/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  vms: [
    'vms/index',
    'vms/opredeleniya',
    'vms/klassifikatsiya-polimerov',
    'vms/vazhnejshie-polimery',
    {
      type: 'category',
      label: 'Полимеризация',
      items: [
        'vms/polimerizaciya',
        'vms/radikalnaya-polimerizaciya',
        'vms/radikalnaya-sopolimerizatsiya',
        'vms/kationnaya-polimerizatsiya',
        'vms/anionnaya-polimerizatsiya',
        'vms/anionno-koordinatsionnaya-polimerizatsiya',
        'vms/stupenchataya-polimerizatsiya',
        'vms/sposoby-provedeniya-polimerizatsii',
      ],
    },
    'vms/polikondensatsiya',
    {
      type: 'category',
      label: 'Реакции звеньев',
      items: [
        'vms/polimeranalogichnye-prevrashcheniya',
        'vms/vnutrimolekulyarnye-prevrashcheniya',
      ],
    },
    {
      type: 'category',
      label: 'Реакции макромолекул',
      items: [
        'vms/reakcii-destrukcii',
        'vms/reakcii-sshivaniya',
      ],
    },
    {
      type: 'category',
      label: 'Структура полимеров',
      items: [
        'vms/gibkost-cepi-polimera',
      ],
    },
  ],

};

module.exports = sidebars;
